#参考 https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html

##数据源
#spring:
#  datasource:
#    dynamic:
#      primary: master
#      strict: true
#      datasource:
#        master:
#          url: jdbc:mysql://localhost:3306/questionnaire?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#          username: root
#          password: root
#          type: com.zaxxer.hikari.HikariDataSource
#          driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: localhost
#    port: 6379

#数据源

spring:
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          url: jdbc:mysql://bv2rebwf6zzsv341.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/xkb37t4b3twhf2ab?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
          username: yauh4v1kuy48gz7m
          password: dbon5yy5j6dah36y
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: redis-12823.c10.us-east-1-2.ec2.cloud.redislabs.com
    port: 12823
    password: 73yR9qLzzO11u21NKubSfVwcpUKWol5C

#日志
logging:
  file:
    path: D:\project\questionnaire\questionnaire-service\logs

#文件信息
file:
  base-url: https://questionnaire-service-8423a5c6bce1.herokuapp.com/service/  #访问地址
  base-dir: D:\project\questionnaire\questionnaire-service\uploads #存储目录
