#参考 https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html

#数据源
spring:
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/questionnaire?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
          username: root
          password: root
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379

#日志
logging:
  file:
    path: D:\project\questionnaire\questionnaire-service\logs

#文件信息
file:
  base-url: http://localhost:8090/service/  #访问地址
  base-dir: D:\project\questionnaire\questionnaire-service\uploads #存储目录
